version: '3'

services:
  app-rabbitmq:
    image: mujic0000/app-rabbitmq:v1.0
    restart: always
    build: ./
    links:
      - rabbitmq
    ports:
      - 8080:8080

  rabbitmq:
    image: library/rabbitmq:latest
    restart: always
    ports:
      - 5672
    environment: 
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_VHOST: localhost